CREATE TABLE ROOM
(
    ID                  NUMBER PRIMARY KEY,
    NUMBER_OF_GUESTS    NUMBER CHECK (NUMBER_OF_GUESTS > 0 ),
    PRICE               DECIMAL CHECK (PRICE >= 0 ),
    BREAKFAST_INCLUDED  NUMBER CHECK (BREAKFAST_INCLUDED IN (1, 0)),
    PETS_ALLOWED        NUMBER CHECK (PETS_ALLOWED IN (1, 0)),
    DATE_AVAILABLE_FROM DATE,
    HOTEL_ID            NUMBER,
    CONSTRAINT HOTEL_FK FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL (ID)
);
