CREATE TABLE ROOM
(
    ID                  NUMBER PRIMARY KEY,
    NUMBER_OF_GUESTS    NUMBER CHECK (NUMBER_OF_GUESTS > 0),
    PRICE               NUMBER(*, 2) CHECK (PRICE >= 0),
    BREAKFAST_INCLUDED  NUMBER(1) CHECK (BREAKFAST_INCLUDED IN (0, 1)),
    PETS_ALLOWED        NUMBER(1) CHECK (PETS_ALLOWED IN (0, 1)),
    DATE_AVAILABLE_FROM DATE NOT NULL,
    HOTEL_ID            NUMBER,
    CONSTRAINT HOTEL_FK FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL (ID)
);

