CREATE TABLE ORDERS
(
    ID         NUMBER PRIMARY KEY,
    USER_ID    NUMBER,
    ROOM_ID    NUMBER,
    DATE_FROM  DATE NOT NULL,
    DATE_TO    DATE NOT NULL,
    MONEY_PAID NUMBER(*, 2),
    CONSTRAINT USER_FK FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    CONSTRAINT ROOM_FK FOREIGN KEY (ROOM_ID) REFERENCES ROOM (ID)
)